Repository atoum/atoum, pull requests merged in 2018-03, with the labels that each got.

#744 feat: Assert on mock arguments
  classes/asserters/adapter.php
  classes/asserters/adapter/call.php
  classes/test.php
  classes/test/adapter/call.php
  classes/test/adapter/calls.php
  tests/units/classes/asserter/resolver.php
Labels: enhancement

#792 Take care to reset relative URL to prevent issues; fixes #783
  classes/report/fields/runner/coverage/html.php
Labels: bug, in progress

#800 doc(readme) Remove the old “list” of contributors
  README.md
Labels: enhancement, in progress
